version: "3.8"

services:
  datbase_posgres:
    image: postgres
    container_name: task-manager
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=task-manager
    volumes:
      - my-db:/var/lib/postgresql/data
volumes:
  my-db:
