version: '3.9'

services:
  database_mongo:
    image: mongo
    container_name: db_task
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=docker
    volumes:
      - ./data:/data/db
